### ISSUE TITLE
ModuleNotFoundError: No module named 'pam'

### ISSUE THREAD

**Issue by Chillstice** [Grimston/LinuxGamePanel#1]
Even though I have pam 1.8.4 installed on my linux mint 19.1 machine, when I run start_web_panel.sh I get the following message printed to the log:
`Traceback (most recent call last):
  File "./lgpl.py", line 14, in <module>
    import pam
ModuleNotFoundError: No module named 'pam'`

I reinstalled python and pam and I even tried disabling pam in the config.
It just refuses to import pam.

**Comment by Grimston** [comment]
Which python versions do you have installed?

**Comment by Chillstice** [comment]
I'm finding it difficult to get all the installed versions, but I definitely know that I have the following:
Python 2.7.15rc1
Python 3.6.7

**Comment by Grimston** [comment]
Try insalling `python-pam` via `pip` and let me know if it runs.
