### ISSUE TITLE
Password Dsnt match

### ISSUE THREAD

**Issue by EsinahkaEs** [Grimston/LinuxGamePanel#3]
Hi, I cant get this to work.
Password dosnt match, I did change the deffault password but it keep complaining that dosnt match. Also try the deffault ones.
Any tip?

**Comment by Grimston** [comment]
PAM authentication is enabled by default, have you tried the game servers username/password with it?

Otherwise, you can disable PAM and use the configurable username and password.
Information on the configuration is available here: https://github.com/Grimston/LinuxGamePanel/wiki/Configuration

**Comment by EsinahkaEs** [comment]
thx, figured it early today :D.
Now im getting this error?

Command Output

[ .... ] Stopping vhserver: Checking for log files
[ INFO ] Stopping vhserver: Checking for log files: Creating log files
installing log dir: /home/pantemaa/log...OK
installing LinuxGSM log dir: /home/pantemaa/log/script...FAIL
creating LinuxGSM log: /home/pantemaa/log/script/vhserver-script.log...FAIL

[ ERROR ] Stopping vhserver: No exit code set

Trying to setup an Valheim server..

**Comment by Grimston** [comment]
Interesting... is the server working via SSH?
